[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends._legacy:_Backend"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term --cov-report=html --no-cov-on-fail"
filterwarnings = [
    "ignore::starlette.exceptions.StarletteDeprecationWarning",
]
testpaths = ["test"]

[tool.coverage.run]
source = ["app"]
omit = ["*/test*", "*/__pycache__/*"]

[tool.coverage.report]
show_missing = true
skip_covered = true
